baseurl = "http://rajeshhegde.com"
languageCode = "en-us"
title = "RH.io"
theme = "hyde"
copyright = "Rajesh Hegde"
publishdir = "rajeshhegde.github.io"

[Author]
	name = "Rajesh Hegde"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "extravaganza of Rajesh Hegde"
	siteDescription = "Personal website of Rajesh Hegde"
	twitter = "https://twitter.com/rajeshphegde"
	github = "https://github.com/RajeshHegde"
	googlePlus = "https://plus.google.com/105779623595863818485"
	disqus = "rajeshhegde"
	googleAnalytics = "UA-68080900-1"